### ISSUE TITLE
.studio is too generic

### ISSUE THREAD

**Issue by devsnek** [javascript-studio/studio-cli#2]
can it be changed to be more specific so that there won't be any overlap between existing programs

**Comment by mantoni** [comment]
Sure, the CLI already looks in different directories for the file, so we can also add variations of the filename, e.g. `.javascript-studio`?

Just curious, which other program do you have installed that uses this name?

**Comment by devsnek** [comment]
i don't personally have any other programs with that name but my inner security researcher just screamed out. also possibly in the next breaking change rename the cli symlink?
